[supervisord]
nodaemon=true

[program:api]
command=uvicorn api_server:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:actions]
command=rasa run actions --port 5055
directory=/app/rasa
environment=PYTHONPATH="/app",BACKEND_PROVIDER="local_api",API_BASE_URL="http://127.0.0.1:8000"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:rasa]
command=rasa run --enable-api --cors "*" --model /app/models/20260407-195925-global-exchange.tar.gz --credentials /app/rasa/credentials.yml --endpoints /app/rasa/endpoints.yml --port 5005
directory=/app/rasa
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:web]
command=python /app/app.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr